import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const data=JSON.parse(readFileSync('data/dictionary.json','utf8'));
test('desktop + mobile: create, QR, join, ready, play, explanation, reload',async({browser})=>{
 const desktop=await browser.newContext({viewport:{width:1440,height:1000}});
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const host=await desktop.newPage(),guest=await mobile.newPage();
 const errors:string[]=[];host.on('pageerror',e=>errors.push(e.message));guest.on('pageerror',e=>errors.push(e.message));
 await host.goto('/');await expect(host.getByRole('heading',{name:'끝말잇기'})).toBeVisible();
 await expect(host.locator('.brand')).toHaveText('↔이어');
 await expect(host.locator('body')).not.toContainText('심장은 더');
 await expect(host.locator('body')).not.toContainText('친구와 실시간 끝말잇기');
 await expect(host.locator('footer')).toHaveText('사전 출처');
 await host.screenshot({path:'test-results/home-desktop.png',fullPage:true});
 await host.getByLabel('닉네임').fill('동현');await host.getByRole('button',{name:'새로운 방 만들기'}).click();
 await expect(host.getByRole('heading',{name:'대기방'})).toBeVisible();
 await host.getByLabel('라운드 수').selectOption('1');
 const room=new URL(host.url()).searchParams.get('room')!;expect(room).toHaveLength(6);
 await expect(host.locator('#qr')).toHaveAttribute('src',/^data:image\/png/);
 await expect(host.getByRole('button',{name:'게임 시작'})).toBeDisabled();
 await guest.goto(`/?room=${room}`);await guest.getByLabel('닉네임').fill('민지');await guest.getByRole('button',{name:'이 방에 입장하기'}).click();
 await expect(guest.getByRole('heading',{name:'대기방'})).toBeVisible();
 await expect(host.locator('.player-card').filter({hasText:'민지'})).toBeVisible();
 await host.screenshot({path:'test-results/lobby-desktop.png',fullPage:true});await guest.screenshot({path:'test-results/lobby-mobile.png',fullPage:true});
 await host.getByRole('button',{name:'준비하기',exact:true}).click();await guest.getByRole('button',{name:'준비하기',exact:true}).click();
 await expect(host.getByRole('button',{name:'게임 시작'})).toBeEnabled();await host.getByRole('button',{name:'게임 시작'}).click();
 await expect(host.locator('.arena')).toBeVisible();await expect(host.locator('.next-letter-panel')).toBeVisible();await expect(guest.locator('.arena')).toBeVisible();
 await expect(host.locator('#timer-label')).toHaveText('남은 시간',{timeout:6000});
 const active=(await host.locator('#turn-label').textContent())==='지금 내 차례'?host:guest;
 await expect(active.locator('.turn-banner')).toContainText('내 차례');
 const starts=(await active.locator('.word-prompt b').innerText()).split(' / ');
 const initial=(await active.getByTestId('current-word').innerText()).replace(/\s/g,'');
 const next=data.entries.find((e:any)=>starts.includes(e.firstSyllable)&&e.reading!==initial);
 await active.getByLabel('끝말잇기 단어').fill('등록되지않은단어쀍쀍');
 await active.locator('#word-input').press('Enter');
 await expect(active.getByRole('alert')).toContainText('정답이 아닙니다');
 await expect(active.locator('#word-input')).toHaveAttribute('aria-invalid','true');
 await expect(active.locator('#word-input')).toHaveValue('등록되지않은단어쀍쀍');
 await active.screenshot({path:'test-results/invalid-answer.png',fullPage:true});
 await expect(active.locator('.round-label')).toHaveText('0 WORDS CONNECTED');
 await active.getByLabel('끝말잇기 단어').fill(next.label);
 await active.locator('#word-input').dispatchEvent('compositionstart');
 await active.locator('#word-input').dispatchEvent('keydown',{key:'Enter',isComposing:true});
 await expect(active.locator('.round-label')).toHaveText('0 WORDS CONNECTED');
 await active.locator('#word-input').dispatchEvent('compositionend');

 await expect(active.getByRole('alert')).toHaveCount(0);
 await expect(host.locator('.round-label')).toHaveText('1 WORDS CONNECTED');await expect(guest.locator('.round-label')).toHaveText('1 WORDS CONNECTED');
 const other=active===host?guest:host;
 await other.locator('#word-input').fill('없는단어쀍');
 await expect(other.locator('#word-input')).toHaveAttribute('enterkeyhint','send');
 await other.locator('#word-input').evaluate(el=>el.dispatchEvent(new InputEvent('beforeinput',{inputType:'insertLineBreak',bubbles:true,cancelable:true})));
 await expect(other.getByRole('alert')).toContainText('정답이 아닙니다');
 await host.locator('.dictionary-panel summary').click();await expect(host.locator('.meaning-list article').first()).toBeVisible();
 await host.screenshot({path:'test-results/game-desktop.png',fullPage:true});await guest.screenshot({path:'test-results/game-mobile.png',fullPage:true});
 await guest.reload();await expect(guest.locator('.arena, .result-card')).toBeVisible();await expect(host.locator('.player-card, .result-players > div')).toHaveCount(2);
 await expect(host.locator('.result-card')).toBeVisible({timeout:10000});await expect(guest.locator('.result-card')).toBeVisible();
 await host.screenshot({path:'test-results/result-desktop.png',fullPage:true});
 expect(errors).toEqual([]);
 const overflow=await guest.evaluate(()=>document.documentElement.scrollWidth>innerWidth);expect(overflow).toBe(false);
 await desktop.close();await mobile.close();
});
test('mobile home and invalid invitation',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/?room=ZZZZZZ');
 await page.screenshot({path:'test-results/home-mobile.png',fullPage:true});
 await page.getByLabel('닉네임').fill('친구');await page.getByRole('button',{name:'이 방에 입장하기'}).click();
 await expect(page.getByRole('status')).toContainText('방을 찾을 수 없어요');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});

test('host can kick a guest and guest returns home without reconnecting',async({browser})=>{
 const a=await browser.newContext(),b=await browser.newContext();
 const host=await a.newPage(),guest=await b.newPage();
 await host.goto('/');await host.getByLabel('닉네임').fill('방장');await host.getByRole('button',{name:'새로운 방 만들기'}).click();
 await expect(host.getByRole('heading',{name:'대기방'})).toBeVisible();
 await guest.goto(host.url());await guest.getByLabel('닉네임').fill('손님');await guest.getByRole('button',{name:'이 방에 입장하기'}).click();
 await expect(host.getByRole('button',{name:'손님 강퇴'})).toBeVisible();
 await expect(guest.locator('.kick-button')).toHaveCount(0);
 host.once('dialog',d=>d.accept());await host.getByRole('button',{name:'손님 강퇴'}).click();
 await expect(guest.getByRole('heading',{name:'끝말잇기'})).toBeVisible();
 await expect(guest.getByRole('status')).toContainText('강퇴');
 expect(await guest.evaluate(()=>sessionStorage.getItem('wordrelay-session'))).toBeNull();
 await expect(host.locator('.player-card:not(.empty)')).toHaveCount(1);
 await guest.reload();await expect(guest.getByRole('heading',{name:'끝말잇기'})).toBeVisible();
 await a.close();await b.close();
});

test('two rounds show automatic transition, cumulative scoreboard and final winner',async({browser})=>{
 test.setTimeout(50000);
 const a=await browser.newContext(),b=await browser.newContext();const host=await a.newPage(),guest=await b.newPage();
 await host.goto('/');await host.getByLabel('닉네임').fill('라운드방장');await host.getByRole('button',{name:'새로운 방 만들기'}).click();
 await host.getByLabel('라운드 수').selectOption('2');
 await guest.goto(host.url());await guest.getByLabel('닉네임').fill('라운드손님');await guest.getByRole('button',{name:'이 방에 입장하기'}).click();
 await expect(guest.getByLabel('라운드 수')).toHaveValue('2');await expect(guest.getByLabel('라운드 수')).toBeDisabled();
 await host.getByRole('button',{name:'준비하기',exact:true}).click();await guest.getByRole('button',{name:'준비하기',exact:true}).click();await host.getByRole('button',{name:'게임 시작'}).click();
 await expect(host.locator('.turn-banner')).toContainText('1 / 2 라운드');
 await expect(host.locator('.round-countdown')).toBeVisible({timeout:12000});
 await host.screenshot({path:'test-results/round-result.png',fullPage:true});
 await expect(host.locator('.turn-banner')).toContainText('2 / 2 라운드',{timeout:7000});
 await expect(host.locator('.result-card h1')).toContainText('우승',{timeout:14000});
 await expect(host.locator('.result-players')).toContainText('300');
 await host.locator('.round-breakdown summary').click();await expect(host.locator('.round-breakdown > div')).toHaveCount(2);
 await host.screenshot({path:'test-results/final-score.png',fullPage:true});await a.close();await b.close();
});

test('offline recovery ejects after six seconds',async({browser})=>{
 const a=await browser.newContext(),b=await browser.newContext();const host=await a.newPage(),guest=await b.newPage();
 await host.goto('/');await host.getByLabel('닉네임').fill('방장');await host.getByRole('button',{name:'새로운 방 만들기'}).click();await expect(host.getByRole('heading',{name:'대기방'})).toBeVisible();
 await guest.goto(host.url());await guest.getByLabel('닉네임').fill('오프라인');await guest.getByRole('button',{name:'이 방에 입장하기'}).click();await expect(guest.getByRole('heading',{name:'대기방'})).toBeVisible();
 const before=Date.now();await b.setOffline(true);
 await expect(guest.getByRole('heading',{name:'끝말잇기'})).toBeVisible({timeout:8500});expect(Date.now()-before).toBeGreaterThanOrEqual(5900);
 await expect(guest.getByRole('status')).toContainText('6초');
 await expect(host.locator('.player-card:not(.empty)')).toHaveCount(1,{timeout:8500});
 await b.setOffline(false);expect(await guest.evaluate(()=>sessionStorage.getItem('wordrelay-session'))).toBeNull();
 await a.close();await b.close();
});
